=== Theodor-Springmann-Stiftung/lenz-briefe/data/xsd/meta.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://lenz-archiv.de"
	xmlns="https://lenz-archiv.de"
	xmlns:lenz="https://lenz-archiv.de"
	elementFormDefault="qualified">

	<xsd:include schemaLocation="common.xsd"></xsd:include>

	<xsd:complexType name="actionattributes">
		<xsd:sequence>
			<xsd:element name="date" type="lenz:date" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="location" type="lenz:ortref" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="person" type="lenz:personref" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="opus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="descriptions">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="letterDesc" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:choice minOccurs="0" maxOccurs="unbounded">
											<xsd:element name="sent" type="actionattributes">
												<xsd:annotation>
													<xsd:documentation> Pflicht: Wann wurde der Brief abgesendet? </xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="received" type="actionattributes">
												<xsd:annotation>
													<xsd:documentation> Pflicht: Wann wurde der Brief empfangen? </xsd:documentation>
												</xsd:annotation>
											</xsd:element>
										</xsd:choice>
										<xsd:element name="hasOriginal" type="lenz:booleanvalue">
											<xsd:annotation>
												<xsd:documentation> Pflicht: Liegt das Original für die Edition vor? </xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="isProofread" type="lenz:booleanvalue">
											<xsd:annotation>
												<xsd:documentation> Pflicht: Wurde der Text anhand der besten verfügbaren
													Quelle kritisch geprüft? </xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="isDraft" type="lenz:booleanvalue">
											<xsd:annotation>
												<xsd:documentation> Pflicht: handelt es sich um einen Entwurf?</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="letter" type="xsd:nonNegativeInteger" use="required" />
								</xsd:complexType>

							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
					<xsd:unique name="uniqueIndexLetter">
						<xsd:annotation>
							<xsd:documentation>Pflicht: Jeder Akteur hat eine eindeutige ID.</xsd:documentation>
						</xsd:annotation>

						<xsd:selector xpath="lenz:letterDesc" />
						<xsd:field xpath="@letter" />
					</xsd:unique>

				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== Theodor-Springmann-Stiftung/lenz-briefe/data/xml/meta.xml
<?xml version='1.0' encoding='UTF-8'?>
<opus xmlns="https://lenz-archiv.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://lenz-archiv.de ../xsd/meta.xsd">
	<descriptions>
		<letterDesc letter="1">
			<sent>
				<date when="1765-01-02">Dorpat (Tartu), 2. Januar 1765</date>
				<location ref="1" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="1" cert="low"></location>
				<!-- Oder Arensburg Hier zwei Orte mit cert low angeben;
				bald und kurz nach nur nach dem bekannten Datum eingeben; cert Attribute für Personen und
				Datum ergänzen; Freitextfeld einfügen; erste 7 Briefe nochmal durchgehen; Adressenleerzeilen
				ergänzen-->
				<person ref="2" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="2">
			<sent>
				<date when="1767-10-11">Dorpat (Tartu), 11. Oktober 1767</date>
				<location ref="1" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="2" />
				<person ref="3" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="3">
			<sent>
				<date when="1767-11-09">Tarwast (Tarvastu), 9. November 1767</date>
				<location ref="2" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="1" />
				<person ref="4" />
				<person ref="5" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="4">
			<sent>
				<date when="1767-11-24">Tarwast (Tarvastu), 24. November 1767</date>
				<location ref="2" />
				<person ref="1" />
				<person ref="3" />
			</sent>
			<received>
				<location ref="1" />
				<person ref="4" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="5">
			<sent>
				<date notBefore="1767-11-24">Dorpat (Tartu), wahrscheinlich Ende Januar 1768 [nach dem 24. Januar]</date>
				<location ref="1" />
				<person ref="1" />
				<person ref="7" />
			</sent>
			<received>
				<location ref="2" />
				<person ref="3" />
				<person ref="6" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="6">
			<sent>
				<date when="1769-10-14">Königsberg (Kaliningrad), 14. Oktober 1769</date>
				<location ref="3" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="1" />
				<person ref="4" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="7">
			<sent>
				<date notBefore="1770-06-01" notAfter="1770-07-01">Dorpat (Tartu), wahrscheinlich Mitte 1770</date>
				<location ref="1" />
				<person ref="4" />
			</sent>
			<received>
				<location ref="3" />
				<person ref="1" />
				<person ref="8" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="true" />
		</letterDesc>

		<letterDesc letter="8">
			<sent>
				<date notBefore="1772-05-15" notAfter="1772-05-30">Fort Louis, Ende Mai 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="9">
			<sent>
				<date when="1772-06-02">Fort Louis, 3. Juni 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="10">
			<sent>
				<date when="1772-06-10">Fort Louis, 10. Juni 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="11">
			<sent>
				<date when="1772-06-15">Fort Louis, 15. Juni 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="1" />
				<person ref="4" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="12">
			<sent>
				<date when="1772-06-28">Fort Louis, 28. Juni 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="13">
			<sent>
				<date when="1772-07-13">Fort Louis, 13. Juli 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="3" />
				<person ref="8" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="14">
			<sent>
				<date notBefore="1772-08-01" notAfter="1772-08-15">Fort Louis, Anfang August 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="15">
			<sent>
				<date notBefore="1772-08-10" notAfter="1772-08-20">Fort Louis, Mitte August 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="16">
			<sent>
				<date when="1772-08-31">Fort Louis, 31. August 1772</date>
				<location ref="4" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="17">
			<sent>
				<date from="1772-10-02" to="1772-10-02">Weißenburg (Wissembourg), 2. September und Landau, 2. Oktober 1772</date>
				<location ref="6" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="1" />
				<person ref="4" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>
		<letterDesc letter="18">
			<sent>
				<date when="1772-09-07">Landau, 7. September 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="19">
			<sent>
				<date when="1772-09-18">Landau, 18. September 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="20">
			<sent>
				<date when="1772-09-24">Arensburg (Kuressaare), 24. September 1772</date>
				<location ref="10" />
				<person ref="8" />
			</sent>
			<received>
				<location ref="4" />
				<person ref="1" />
			</received>
			<hasOriginal value="true" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="21">
			<sent>
				<date notBefore="1772-10-01" notAfter="1772-10-15">Landau, Anfang Oktober 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="22">
			<sent>
				<date notAfter="1772-10-07">Landau, Anfang Oktober 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="23">
			<sent>
				<date notBefore="1772-10-10" notAfter="1772-10-20">Landau, Mitte Oktober 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="24">
			<sent>
				<date notBefore="1772-10-15" notAfter="1772-10-31">Landau, zweite Oktoberhälfte 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="25">
			<sent>
				<date notBefore="1772-10-20" notAfter="1772-08-31">Landau, wahrscheinlich Ende Oktober 1772</date><!--
				Was ist die für "Gegen Ende Oktober" konventionelle Zeitspanne? -->
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
			</received>
			<hasOriginal value="false" />
			<isProofread value="true" />
			<isDraft value="false" />
		</letterDesc>

		<letterDesc letter="26">
			<sent>
				<date notBefore="1772-10-15" notAfter="1772-10-31">Landau, Ende Oktober 1772</date>
				<location ref="5" />
				<person ref="1" />
			</sent>
			<received>
				<location ref="7" />
				<person ref="9" />
