=== Theodor-Springmann-Stiftung/lenz-briefe/data/xsd/references.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://lenz-archiv.de"
	xmlns="https://lenz-archiv.de"
	xmlns:lenz="https://lenz-archiv.de"
	elementFormDefault="qualified">

	<xsd:include schemaLocation="common.xsd"></xsd:include>

	<xsd:element name="opus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="definitions">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="personDefs">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="personDef" minOccurs="0"
											maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:attribute name="index" type="xsd:integer" use="required" />
												<xsd:attribute name="name" type="lenz:NonEmptyString" use="required" />
												<xsd:attribute name="nachname" type="lenz:NonEmptyString" use="optional" />
												<xsd:attribute name="vorname" type="lenz:NonEmptyString" use="optional" />
												<xsd:attribute name="komm" type="lenz:NonEmptyString" use="optional" />
												<xsd:attribute name="ref" type="xsd:anyURI" use="optional" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="locationDefs">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="locationDef" minOccurs="0"
											maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:attribute name="index" type="xsd:integer" use="required" />
												<xsd:attribute name="name" type="lenz:NonEmptyString" use="required" />
												<xsd:attribute name="ref" type="xsd:anyURI" use="optional" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="appDefs">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="appDef" minOccurs="0"
											maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:attribute name="index" type="xsd:integer" use="required" />
												<xsd:attribute name="name" type="lenz:NonEmptyString" use="required" />
												<xsd:attribute name="category" type="lenz:NonEmptyString" use="required" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/lenz-briefe/data/xml/references.xml
<?xml version="1.0" encoding="utf-8"?>
<opus xmlns="https://lenz-archiv.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://lenz-archiv.de ../xsd/references.xsd">
	<definitions>
		<personDefs>
			<personDef index="-1" name="Unbekannt" />
			<personDef index="1" name="Jakob Michael Reinhold Lenz" ref="https://d-nb.info/gnd/118571656"
				vorname="Jakob Michael Reinhold" nachname="Lenz" komm="jmr-lenz" />

			<personDef index="2" name="Friedrich Konrad Gadebusch"
				vorname="Friedrich Konrad" nachname="Gadebusch" komm="gadebusch" />

			<personDef index="3" name="Friedrich David Lenz"
				vorname="Friedrich David" nachname="Lenz" komm="fd-lenz" />

			<personDef index="4" name="Christian David Lenz" ref="https://d-nb.info/gnd/12021363X"
				vorname="Christian David" nachname="Lenz" komm="chd-lenz" />

			<personDef index="5" name="Dorothea Lenz"
				vorname="Dorothea" nachname="Lenz" komm="d-lenz" />

			<personDef index="6" name="Christine Margarethe Lenz"
				vorname="Christine Margarethe" nachname="Lenz" komm="chm-lenz" />

			<personDef index="7" name="Obristin von Albedyll"
				vorname="NN" nachname="von Albedyl" komm="albedyll" />

			<personDef index="8" name="Johann Christian Lenz"
				vorname="Johann Christian" nachname="Lenz" komm="jch-lenz" />

			<personDef index="9" name="Johann Daniel Salzmann" ref="https://d-nb.info/gnd/116777265"
				vorname="Johann Daniel" nachname="Salzmann " komm="salzmann" />

			<personDef index="10" name="Johann Caspar Lavater" ref="http://d-nb.info/gnd/118570293"
				vorname="Johann Caspar" nachname="Lavater" komm="lavater" />

			<personDef index="11" name="Johann Gottfried Röderer" ref="http://d-nb.info/gnd/124456359"
				vorname="Johann Gottfried" nachname="Röderer" komm="röderer" />

			<personDef index="12" name="Johann Wolfgang Goethe" ref="http://d-nb.info/gnd/118540238"
				vorname="Johann Wolfgang" nachname="Goethe" komm="goethe" />

			<personDef index="13" name="Sophie von La Roche" ref="http://d-nb.info/gnd/118569767"
				vorname="Sophie von" nachname="La Roche" komm="la roche" />

			<personDef index="14" name="Friedrich Wilhelm Gotter" ref="http://d-nb.info/gnd/118540939"
				vorname="Friedrich Wilhelm" nachname="Gotter" komm="gotter" />

			<personDef index="15" name="Luise König"
				vorname="Luise" nachname="König" komm="könig" />

			<personDef index="16" name="Karoline von Herder" ref="http://d-nb.info/gnd/118549561"
				vorname="Karoline von" nachname="Herder" komm="herder" />

			<personDef index="17" name="Johann Gottfried von Herder" ref="http://d-nb.info/gnd/118549553"
				vorname="Johann Gottfried von" nachname="Herder" komm="jg-herder" />

			<personDef index="18" name="Johann Georg Schlosser" ref="http://d-nb.info/gnd/118795163"
				vorname="Johann Georg" nachname="Schlosser" komm="schlosser" />

			<personDef index="19" name="Heinrich Julius von Lindau" ref="http://d-nb.info/gnd/117014214"
				vorname="Heinrich Julius von" nachname="Lindau" komm="lindau" />

			<personDef index="20" name="Heinrich Christian Boie" ref="http://d-nb.info/gnd/118661078"
				vorname="Heinrich Christian" nachname="Boie" komm="boie" />

			<personDef index="21" name="Gottlieb Konrad Pfeffel" ref="http://d-nb.info/gnd/118740709"
				vorname="Gottlieb Konrad" nachname="Pfeffel" komm="pfeffel" />

			<personDef index="22" name="Philipp Christoph Kayser" ref="http://d-nb.info/gnd/116090235"
				vorname="Philipp Christoph" nachname="Kayser" komm="kayser" />

			<personDef index="23" name="Johann Konrad Pfenninger" ref="http://d-nb.info/gnd/104318112"
				vorname="Johann Konrad" nachname="Pfenninger" komm="pfenninger" />

			<personDef index="24" name="Hieronymus Peter Schlosser" ref="http://d-nb.info/gnd/117330205"
				vorname="Hieronymus Peter" nachname="Schlosser" komm="hp-schlosser" />

			<personDef index="25" name="Philipp Seidel" ref="http://d-nb.info/gnd/117463639"
				vorname="Philipp" nachname="Seidel" komm="seidel" />

			<personDef index="26" name="Christoph Martin Wieland" ref="http://d-nb.info/gnd/118632477"
				vorname="Christoph Martin" nachname="Wieland" komm="wieland" />

			<personDef index="27" name="Friedrich Leopold Graf Stolberg"
				ref="http://d-nb.info/gnd/1277071357"
				vorname="Friedrich Leopold" nachname="Graf Stolberg" komm="graf stolberg" />

			<personDef index="28" name="Karl Ludwig von Knebel" ref="http://d-nb.info/gnd/118777505"
				vorname="Karl Ludwig von" nachname="Knebel" komm="knebel" />

			<personDef index="29" name="Johann Heinrich Merck" ref="http://d-nb.info/gnd/118581015"
				vorname="Johann Heinrich" nachname="Merck" komm="merck" />

			<personDef index="30" name="Friederike Hesse" ref="http://d-nb.info/gnd/143459023"
				vorname="Friederike" nachname="Hesse" komm="hesse" />

			<personDef index="31" name="Christian Heinrich Schmid" ref="http://d-nb.info/gnd/116697105"
				vorname="Christian Heinrich" nachname="Schmid" komm="schmid" />

			<personDef index="32" name="Henriette von Oberkirch geb. Waldner von Freundstein"
				ref="http://d-nb.info/gnd/124494692"
				vorname="Henriette-Luise von" nachname="Oberkirch" komm="oberkirch" />

			<personDef index="33" name="Verlag Weidmanns Erben und Reich"
				ref="http://d-nb.info/gnd/6146596-3"
				vorname="NN" nachname="NN" komm="verlag weidmanns erben und reich" />

			<personDef index="34" name="Johann Friedrich Simon" ref="http://d-nb.info/gnd/1076372430"
				vorname="Johann Friedrich" nachname="Simon" komm="simon" />

			<personDef index="35" name="Friedrich Müller (Maler Müller)"
				vorname="Friedrich" nachname="Müller" komm="müller" />

			<personDef index="36" name="Johann August von Kalb" ref="http://d-nb.info/gnd/11602898X"
				vorname="Johann August von" nachname="Kalb" komm="kalb" />

			<personDef index="37" name="Friedrich Hildebrand von Einsiedel"
				ref="http://d-nb.info/gnd/118681818"
				vorname="Friedrich Hildebrand von" nachname="Einsiedel" komm="einsiedel" />

			<personDef index="38" name="Luise von Göchhausen"
				vorname="Luise von" nachname="Göchhausen" komm="göchhausen" />

			<personDef index="39" name="Ramond de Carbonnières"
				vorname="Ramond de" nachname="Carbonnières" komm="carbonnières" />

			<personDef index="40" name="Wilhelm Gottlieb Becker" ref="http://d-nb.info/gnd/115833706"
				vorname="Wilhelm Gottlieb" nachname="Becker" komm="becker" />

			<personDef index="41" name="Charlotte von Stein" ref="http://d-nb.info/gnd/118617222"
				vorname="Charlotte von" nachname="Stein" komm="stein" />

			<personDef index="42" name="Anna Marie Laudt"
				vorname="Anna Marie" nachname="Laudt" komm="am-laudt" />

			<personDef index="43" name="Susanne Margareta Laudt"
				vorname="Susanne Margareta" nachname="Laudt" komm="sm-laudt" />

			<personDef index="44" name="Theobald Marchand"
				vorname="Theobald" nachname="Marchand" komm="marchand" />

			<personDef index="45" name="Johann Friedrich Wilhelm Christian Schenck"
				ref="http://d-nb.info/gnd/102948256X"
				vorname="Johann Friedrich Wilhelm Christian" nachname="Schenck" komm="schenck" />

			<personDef index="46" name="Friedrich Maximilian Klinger" ref="http://d-nb.info/gnd/118563319"
				vorname="Friedrich Maximilian" nachname="Klinger" komm="klinger" />

			<personDef index="47" name="Christian Wilhelm Gottlob von Wilkau"
				vorname="Christian Wilhelm Gottlob von" nachname="Wilkau" komm="wilkau" />

			<personDef index="48" name="Friedrich Philipp Eisenberg" ref="http://d-nb.info/gnd/1157686966"
				vorname="Friedrich Philipp" nachname="Eisenberg" komm="eisenberg" />

			<personDef index="49" name="Heinrich Jakob Lenz und dessen Bruder"
				vorname="Heinrich Jakob" nachname="Lenz" komm="hj-lenz" />

			<personDef index="50" name="Isaak Haffner" ref="http://d-nb.info/gnd/116370238"
				vorname="Isaak" nachname="Haffner" komm="haffner" />

			<personDef index="51" name="Johann Georg Zimmermann" ref="http://d-nb.info/gnd/1186369798"
				vorname="Johann Georg" nachname="Zimmermann" komm="zimmermann" />

			<personDef index="52" name="Herzogin Anna Amalia" ref="http://d-nb.info/gnd/118649485"
				vorname="Anna" nachname="Amalia" komm="amalia" />

			<personDef index="53" name="Philipp Erasmus Reich" ref="http://d-nb.info/gnd/118809334"
				vorname="Philipp Eramus" nachname="Reich" komm="reich" />

			<personDef index="54" name="Herzog Karl August" ref="http://d-nb.info/gnd/118968173"
				vorname="Karl" nachname="August" komm="august" />

			<personDef index="55" name="Emanuel Friedrich Mayer" ref="http://d-nb.info/gnd/1203107382"
				vorname="Emanuel Friedrich" nachname="Mayer" komm="mayer" />

			<personDef index="56" name="Johann Georg Neukirch" ref="http://d-nb.info/gnd/116956038"
				vorname="Johann Georg" nachname="Neukirch" komm="neukirch" />

			<personDef index="57" name="Karl August Küttner" ref="http://d-nb.info/gnd/100615104"
				vorname="Karl August" nachname="Küttner" komm="küttner" />

			<personDef index="58" name="Johann Heinrich Füssli" ref="http://d-nb.info/gnd/136012159"
				vorname="Johann Heinrich" nachname="Füssli" komm="füssli" />

			<personDef index="59" name="Carl Ulysses von Salis-Marschlins"
				ref="http://d-nb.info/gnd/100263690"
				vorname="Carl Ulysses" nachname="von Salis-Marschlins" komm="von salis-marschlin" />

			<personDef index="60" name="Johann Kaspar Hirzel" ref="http://d-nb.info/gnd/128695862"
				vorname="Johann Kaspar" nachname="Hirzel" komm="hirzel" />

			<personDef index="61" name="Christina Margaretha Lenz"
				vorname="Christina Margaretha" nachname="Lenz" komm="chrm-lenz" />

			<personDef index="62" name="George Behrens"
				vorname="Behrens" nachname="George" komm="behrens" />

			<personDef index="63" name="Peuker"
				vorname="NN" nachname="Peuker" komm="peuker" />

			<personDef index="64" name="Friederike Brion" ref="http://d-nb.info/gnd/118515500"
				vorname="Friederike" nachname="Brion" komm="brion" />

			<personDef index="65" name="Christian Brion"
